bind_addr = "localhost:8080"
log_level = "debug"
database_url = "host=localhost user=postgres password=postgres dbname=restapi_dev sslmode=disable"
session_key = "asdofijaodsfijaosdjfaoijsfoiajosdfijaosijfoaisjdfi"